### ISSUE TITLE
Neo4j source connector data transform is not valid for elastic sink or any other sink except neo4j

### ISSUE THREAD

**Issue by farhadnowzari** [neo4j/neo4j-kafka-connector#182]
I have updated our neo4j connector to version 5.1.1 and now I see the data produced by the source connector is like 

```
Struct{id=Struct{S=training},modifiedUtc=Struct{I64=1725965750415}}
```
I am using the `StringConverter`.

This `Struct` format, is not supported by any sink connector. Is there any SMT needed in between to transform the data to a normal json?

Also tried with JsonConverter and Avro, but no difference.

**Comment by Emrehzl94** [comment]
Yes, and you can use ksqlDB for the transformation.

**Comment by Romsick** [comment]
Are we right to understand that the Source connector from 5.1 onwards, even with Query strategies, there is and will no longer be a configuration to allow for the messages to come as simple schema-less JSONs without including the schema on each field as a struct? And this option is not in the roadmap for the newer >5.1 versions?

In 5.1.0-rc01 changelog there is a mention:
> To disable schemas, configure your key and value converters accordingly.

But this doesn't seem to be possible anymore. And it's a bit concerning having to depend on ksqlDB or other stream processing tools to continue supporting replication of Neo4j (4.4) to other DBs with the connector on Query mode.

**Comment by Emrehzl94** [comment]
Hi @Romsick,

You are correct that starting from version 5.1, the source connector behavior has changed, and the option to send schema-less JSONs with simple field values is currently unavailable. However, I wanted to clarify that we will bring this feature back, and we're actively working on it. It's expected to be included in one of the upcoming releases, most likely the next one. With the solution, you will be able to decide what type of structure you want to use, so there is not gonna be a need for ksqlDB or any kind of manual data parsing solutions.

**Comment by Romsick** [comment]
Thanks for clarifying, that's great to hear, we will be paying attention to future releases!

**Comment by Emrehzl94** [comment]
Here is the latest release of the connector; https://github.com/neo4j/neo4j-kafka-connector/releases/tag/5.1.5
and the documentation about the feature; https://neo4j.com/docs/kafka/current/source/payload-mode/

I'm closing this issue now, and please feel free to create another one if anything comes up. Thanks!
